[tool.poetry]
name = "clip"
version = "0.1.0"
description = ""
authors = ["Anyang Peng"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
torch = "^2.3.1"
pytest = "^8.2.2"
einops = "^0.8.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
