name: CI Workflow for Unit Tests
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
      
      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install poetry
        run: |
            curl -sSL https://install.python-poetry.org | python - --version 1.2.2
            poetry install
        working-directory: clip

      - name: Run tests
        run: poetry run pytest --cov=clip --cov-report=xml:clip/coverage.xml
        working-directory: clip
        
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          files: clip/coverage.xml
          verbose: true
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
